version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./Server/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./Client/
      dockerfile: DockerfileProd
    environment:
        VITE_PUBLIC_IP: ${IP_ADDRESS}
    ports:
      - "80:80"
    restart: always
    expose:
      - "80"